version: 1.0.{build}

install:
   - nuget restore


build:
  project: NotifcationService.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: normal

environment:
  COVERALLS_REPO_TOKEN:
    secure: YReKoFOo8QnLltuWGlzhKoxlIufOLPDrSdE+aHArUMhMn/B78j6nqmq8gWM5J1ds

after_test:
# generate report for MSTest testing framework:
    - cmd: packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\MSTest.exe" -targetargs:"/testcontainer:NotificationService.Tests/bin/debug/NotificationService.Tests.dll" -output:coverage.xml

    - cmd: packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml

notifications:
- provider: Email
  to:
  - eldhoabe.07@gmail.com
  subject: Notification service git hub application failed
  message: There is build failure in the notification service
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false